#!/bin/bash
# pmset-helper - runs pmset commands without password
# Install as: sudo cp pmset-helper /usr/local/bin/ && chmod +x /usr/local/bin/pmset-helper
# Add to /etc/sudoers: %admin ALL=(root) NOPASSWD: /usr/local/bin/pmset-helper

case "$1" in
    sleep)
        sudo pmset -a tcpkeepalive 0 proximitywake 0 standby 1 standbydelayhigh 3600 standbydelaylow 3600
        sudo pmset -a powernap 0 womp 0 ttyskeepawake 0 sleepservices 0 magicwake 0
        ;;
    wake)
        sudo pmset -a tcpkeepalive 1 proximitywake 1 standby 1 standbydelayhigh 3600 standbydelaylow 3600
        sudo pmset -a powernap 0
        ;;
    aggressive)
        sudo pmset -a disksleep 1 autopoweroff 1 powernap 0
        ;;
    reset)
        sudo pmset -a powernap 1 womp 1
        ;;
    *)
        exit 1
        ;;
esac